apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "dbcharts.labels" . | nindent 4 }}
  namespace: voting-app
  name: {{ .Values.db.containers.name}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "dbcharts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dbcharts.labels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.db.image.repository }}
        name: {{ .Values.db.containers.name}}
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: {{ .Values.db.service.port }}
          name: {{ .Values.db.containers.name}}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 