apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vote.service.name | quote }}
  namespace: {{ .Values.vote.service.namespace | quote}}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - name: "vote-service"
      port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.service.targetport }}
      nodeport: {{ .Values.vote.service.nodeport }}
      protocol: TCP
      name: http
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.vote.service.namespace | quote}}
  name: ingress-alb-vote
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  tls:
  - hosts:
    - vote-nextgends-rac3.axle-interns.com
    secretName: vote-cert
  ingressClassName: alb
  rules:
    - host: vote-nextgends-rac3.axle-interns.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: vote
              port:
                number: 5000    
