apiVersion: v1
kind: Namespace
metadata:
  name: voting-app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  namespace: voting-app2
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: 853931821519.dkr.ecr.us-east-1.amazonaws.com/devsecops-rac3-registry:postgres
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
