apiVersion: "v1"
kind: "Service"
metadata:
  name: "vote-internal"
  namespace: "voting-app"
  labels:
    app: vote
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  selector:
    app: "vote"
  type: "ClusterIP"