apiVersion: v1
kind: Service
metadata:
  name: vote-internal
  namespace: voting-app1
  labels:
    app: vote
spec:
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 80
  selector:
    app: vote
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: result-internal
  namespace: voting-app1
  labels:
    app: result
spec:
  ports:
    - protocol: "TCP"
      port: 5001
      targetPort: 80
  selector:
    app: result
  type: ClusterIP