apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  namespace: voting-app2
  name: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31002
    protocol: TCP
  selector:
    app: vote
