<<<<<<< HEAD
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: vote
#   namespace: voting-app
#   name: vote
# spec:
#   type: NodePort
#   ports:
#   - name: "vote-service"
#     port: 5000
#     targetPort: 80
#     nodePort: 31000
#     protocol: TCP
#     name: http
#   selector:
#     app: vote
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: voting-app
#   name: ingress-vote-result
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
# spec:
#   ingressClassName: alb
#   rules:
#     - host: nextgends-rac3.axle-interns.com
#       http:
#         paths:
#         - path: /vote
#           pathType: Prefix
#           backend:
#             service:
#               name: vote
#               port:
#                 number: 5000


# apiVersion: v1
# kind: Service
# metadata:
#   namespace: voting-app
#   name: vote
# spec:
#   ports:
#     - port: 5000
#       targetPort: 80
#       protocol: TCP
#   type: NodePort
#   selector:
#     app: vote


apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: voting-app
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
=======
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  namespace: voting-app
  name: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: voting-app
  name: ingress-vote
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: vote
              port:
                number: 5000
>>>>>>> 8586731 (added as per alb requirement)
